% This is the matlab code to plot the data generated by the rolling average test program

% Load the data from the CSV file
data = readtable('data.csv');
% Extract the raw and filtered coordinates
raw_coords = [data.Raw_X, data.Raw_Y, data.Raw_Z];
filtered_coords = [data.Filtered_X, data.Filtered_Y, data.Filtered_Z];
% Create a 3D plot with two paths
figure;
hold on;
plot3(raw_coords(:,1), raw_coords(:,2), raw_coords(:,3), '-o', 'Color', 'b', 'LineWidth', 1.5, 'MarkerSize', 5);
plot3(filtered_coords(:,1), filtered_coords(:,2), filtered_coords(:,3), '-o', 'Color', 'r', 'LineWidth', 1.5, 'MarkerSize', 5);
% Set axis labels
xlabel('X-axis');
ylabel('Y-axis');
zlabel('Z-axis');
% Set font size
set(gca, 'FontSize', 14);
% Set equal axis scaling
axis equal;
% Add minor grids
grid(gca, 'minor');
% Add legends
legend('Raw data', 'Filtered data', 'Location', 'best');
hold off;
